### ISSUE TITLE
Flex props doesn't work properly

### ISSUE THREAD

**Issue by Kikobeats** [jxnblk/grid-styled#120]
Hello,

I noted that now `Flex` is based on `Box` component: https://github.com/jxnblk/grid-styled/blob/master/src/Flex.js

Something is not working properly because when I use a `Box` component, the HTML tag rendered looks fine and the style are correctly applied:

```html
<footer class="sc-bwzfXH eYUrDm" role="contentinfo" flexdirection="column"></footer>
```

However, using `Flex` looks like it can't clean the specific props from the HTML tag, also styled are not applied properly

```html
<footer class="sc-htpNat irXZyd" role="contentinfo" pt="1" bg="darkBlue900"></footer>
``` 

I monkey patch my code in local following the [old way](https://github.com/jxnblk/grid-styled/commit/b58dbbcd4a6d1934157fb913d051711098575d96#diff-536fc7306c4dbbc05c91c9d209661a6fL14):

```jsx
const Flex = styled(Box)([],
  { display: 'flex' },
  display,
  textAlign,
  maxWidth
)

Flex.defaultProps = {
  textAlign: 'inherit',
  blacklist: [...Object.keys(FlexBase.propTypes), 'textAlign']
}

export default Flex
```

Now is working fine. I suppose the problem is the `is` inheritance

**Comment by HipsterBrown** [comment]
I encountered this issue after updating as well. 

>  I suppose the problem is the `is` inheritance

Based on my digging, I believe this is correct since the new implementation of `Flex` uses the `system` function from `system-components` with `is` set as `Box` by default, so the style props that Box uses is passed to that component. When the `is` prop is overridden on `Flex` in use, i.e. `<Flex is="footer" />` for you, then the Box component is no longer the underlying tag for the Flex component. 

Whereas `styled(Box)` [creates a new class based on the original Box component](https://www.styled-components.com/docs/faqs#when-should-i-use-styled), `system({ is: Box })` just creates a new component with the `is` prop passed to `clean-tag`. There should be a way to extend a system-component, rather than using the `is` prop.

**Comment by Kikobeats** [comment]
I think that the only thing necessary is to add `Component` support at `clean-tag` level.

Also this will be equivalent to how to handle extend component at styled components universe, where you can exted from a component

```
const CustomBox = styled(Box)`
`
```

**Comment by jxnblk** [comment]
Thanks! I suspect the clean-tag component needs a type check to determine whether or not to pass the `is` prop through or another way to handle extensions. I’ll add some failing tests for this use case
