### ISSUE TITLE
Fall back to inline-block if flexbox is not supported

### ISSUE THREAD

**Issue by dagda1** [jxnblk/grid-styled#19]
How would you feel about a PR that made inline-block was a fallback rather than having to declare whether to use `Flex` or `Grid`?

**Comment by jxnblk** [comment]
Personally I'd rather keep that out of this project since inline-block and flex box behave quite differently, and I would imagine that most users wouldn't want/need to use a fallback feature. That said, I could imagine that a fallback grid component could be composed from this library (i.e. as another npm package) for people who *do* want it - hope that makes sense

**Comment by dagda1** [comment]
I'm working on such a component.  Really liking the grid!
