### ISSUE TITLE
Unable to pass ref to DOM node

### ISSUE THREAD

**Issue by alexanbj** [jxnblk/grid-styled#44]
Not sure if this is the correct place to create this issue, or in the tag-hoc issue, but here it goes anyways.

I'm unable to get a React ref to the DOM nodes these components create. For instance, when passing `innerRef` to `<Box /`, it is tag-hoc's Base that gets the ref, not the div underneath.

<img width="568" alt="screen shot 2017-09-18 at 12 12 44" src="https://user-images.githubusercontent.com/81577/30537948-1aa66146-9c6c-11e7-93c0-77a2349f2d83.png">

I would also like to thank you for this library. I'm using it together with [styled-system](https://github.com/jxnblk/styled-system) in my current project. My styled-components feels so clean and reusable. Many thanks!

**Comment by chrisui** [comment]
Have also bumped into this issue which is a pretty big blocker.

**Comment by chrisui** [comment]
Happy to submit a pull request if we're happy with providing the `innerRef` prop solution à la `styled-components` and `emotion`

**Comment by chrisui** [comment]
After a bit of digging have traced this problem down to `tag-hoc` being a functional component rather than a class (therefore not having an instance and the `ref` prop not working).

The problem is that `grid-styled` does `styled(tag())`. `styled` takes the `innerRef` prop and maps it to a `ref` prop which is passed to the `tag()` component. This fails since it's a functional component.

The simplest fix here is for `tag-hoc` to create a class component so that a `ref` prop can be passed appropriately.

**Comment by chrisui** [comment]
Have submitted a pull request for `tag-hoc` which resolves the issue with refs. https://github.com/jxnblk/tag-hoc/pull/6

**Comment by chrisui** [comment]
We've also fixed this for our usage by simply wrapping in another class component which `ref` can be passed to since our use-case is just to get the root dom node.

cc @alexanbj

**Comment by duro** [comment]
Bumping this again, as it is causing us grief as well

**Comment by jxnblk** [comment]
Although I'd strongly advise against using refs on layout components (curious as to where you're wanting to do this), v3 *should* pass on the `innerRef` prop, but feel free to reopen this issue if not.
