### ISSUE TITLE
Allow border properties on `Box`

### ISSUE THREAD

**Issue by goldcaddy77** [jxnblk/grid-styled#57]
Any thoughts on adding border properties on `Box`?  It's trivial to recreate with `createComponent`, but I figured it might be a nice addition if it's a common use case.

**Comment by Jascha-Sundaresan** [comment]
check out code for the `Flex` component.

`responsiveStyle` is an export of styled-system. You can do this yourself w/ any css property.

Check it out. It's another of jxnblk's libraries. I use it with cxs instead of styled-components, and just build my own `Box`

https://github.com/jxnblk/styled-system#responsivestyle

**Comment by jxnblk** [comment]
Generally I would advise not mixing visual styles with layout components, but you can also use styled-component's `extend` method if you need a one-off style with borders, e.g.:

```jsx
const BorderedBox = Box.extend`
  border-left-width: 1px;
  border-left-style: solid;
  border-left-color: #ccc;
`
```
